$lines = @(
    "[*] Checking system requirements...",
    "[*] OS: Windows $(([System.Environment]::OSVersion.Version))",
    "[OK] PowerShell $($PSVersionTable.PSVersion) detected",
    "[*] Checking Docker...",
    "[OK] Docker is available",
    "[*] Pulling bookstackapp/bookstack:latest ...",
    "latest: Pulling from bookstackapp/bookstack",
    "a3d4f9b2c1e8: Pull complete",
    "7e2c6d1f4a09: Pull complete",
    "3b8a5e7c2d4f: Pull complete",
    "[OK] bookstackapp/bookstack:latest pulled",
    "[*] Pulling mariadb:10.11 ...",
    "10.11: Pulling from library/mariadb",
    "f1c2b9e3d5a7: Pull complete",
    "8d4e6f2a1c3b: Pull complete",
    "[OK] mariadb:10.11 pulled",
    "[*] Generating database credentials...",
    "[OK] DB_PASSWORD generated",
    "[*] Writing docker-compose.yml ...",
    "[OK] docker-compose.yml written",
    "[*] Starting containers...",
    "Creating network bookstack_default",
    "Creating bookstack_db_1  ... done",
    "Creating bookstack_app_1 ... done",
    "[*] Waiting for database to be ready",
    "[.] Attempt 1/10 - not ready yet...",
    "[.] Attempt 2/10 - not ready yet...",
    "[.] Attempt 3/10 - not ready yet...",
    "[OK] Database is ready",
    "[*] Running BookStack migrations...",
    "[OK] Migrations complete",
    "[*] Setting up admin account...",
    "[OK] Admin email: admin@bookstack.local",
    "[OK] Admin password: changeme123",
    "[*] Configuring nginx reverse proxy...",
    "[OK] nginx config written",
    "[*] Starting nginx...",
    "[OK] nginx started",
    "",
    "============================================",
    "  BookStack installation complete!",
    "  URL: http://localhost:8875",
    "  Login: admin@bookstack.local / changeme123",
    "============================================"
)

foreach ($line in $lines) {
    Write-Output $line
    Start-Sleep -Milliseconds (Get-Random -Minimum 120 -Maximum 600)
}
